### ISSUE TITLE
Can I use this for netcoreapp1.1?

### ISSUE THREAD

**Issue by skynetit** [lmolkova/correlation#15]
Hi, 

I am looking for adding CorrelationId for every incoming request & outgoing request for my netcoreapp1.1 application?. Will I be able to use this?

My idea was to have only one correlationid for all calls. Some thing like , there are 3 services ServiceA calls  ServiceB which calls ServiceC. When a request comes in for ServiceA, it creates a correlationid C1 and when ServiceA calls ServiceB it creates correlationid C2 and the outgoing request will have a header value like C1|C2. When ServiceB calls  ServiceC it will create correlationid C3 with the header value as C1|C2|C3. This will help when I search by C1, I can get all the logs related to the parent correlationid.  

Is there a way to use like above scenario?

**Comment by lmolkova** [comment]
Hi @mailbala 

this repo is abandoned.
Please check new [Actiity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) class in .NET.
It works together with [DiagnosticSource](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md).

This solution is integrated now in .NET Core 2.0 and gives you the way to correlate your traces and restore casuality between them.

HttpClient in .NET Core is instrumented with DiagnosticSource in netcoreapp 1.1 and the instrumentation is updated in netcoreapp 2.0. Here is a diagnostics [guide](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/HttpDiagnosticsGuide.md) for HTTP (for 2.0)

Asp.Net Core on incoming boundary is also [instrumented](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs) with DiagnosticSource.

in .NET Core 1.1 you can still use (deprecated in 2.0) events from DiagnosticSource and with some additional code use Actvity from DiagnosticSource nuget package 4.4.0 to generate ids and flow with the async execution.

**Comment by skynetit** [comment]
@lmolkova Thanks for the information.
Any working sample code to have a look?

**Comment by lmolkova** [comment]
@mailbala 

We do have code in [ApplicationInsights](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-overview) SDKs that consumes the instrumentation.

Here is 
- HTTP Client listener: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs
- AspNetCore listener: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs

You may just use ApplicationInsights if you have Azure subscription. It tracks a lot of things automatically and natively correlates all telemetry.

**Comment by skynetit** [comment]
@lmolkova I don't have azure subscription. In that case, how can I use DiagnosticSource or Activity?

**Comment by lmolkova** [comment]
Yes, you can. It's pure .NET concept.
You can still use AppInsights SDK implementations as a reference. It does some AppInsights specific things and supports multiple versions of instrumentation. You probably don't need everything there, so I would suggest going through Activity, DiagnosticSource and Http guides I referenced first so you would have a general idea.

**Comment by skynetit** [comment]
Thanks @lmolkova
