### ISSUE TITLE
Removal of Filtering logic

### ISSUE THREAD

**Issue by vancem** [lmolkova/correlation#8]
I am strongly skeptical of the filtering logic we currently have (most things in CoorelationConfigurationOptions, but in particular EndpointFilter*.    

The idea is that in theory this will allow you to AVOID adding outgoing ID/Baggage to particular URL targets.   However this is at best a optimization (adding the headers is not that expensive), and it is not clear that filtering by URL pattern is a good idea (who actually knows that particular patterns are OK to not have?).     What drove us to use the default patterns that are there?   Is it a big deal to simply not have that filter (effectively do it for everything)?   

My belief is that other sampling (simply doing one every 100 requests) is far more important than optimizing particular URL targets, and given that the extra complexity of plumbing the URL based filtering is probably not worth it.   

Finally one of the ideas is that filtering is a logging function, not a activity function.  Thus in particular for System.Net.Http (which will only be instrumented with DiagnosticSource, we should be using DiagnosticSource's filtering logic (It has an 'IsEnabled() check).    We should use that and see if that is enough.  

What do you think?   Is it reasonable to simply rip it out the config for activities?

**Comment by lmolkova** [comment]
I agree that URI-based filtering should not be used for performance optimization.
There are some cases where we must not log outgoing requests:
E.g. if logs are sent over HTTP (examples are elasticsearch  and ApplicationInsights). If we don't filter out those requests we would try to log every outgoing request to those services as well which will cause endless recursive calls to logger.
I assume there may be other real world cases where filtering is important just to keep application working.

**Comment by vancem** [comment]
The recursion issue is good to know about.    I note that that issue is actually generic to LOGGING and not to HTTP (networking) or Activities.   You have the problem any time your logging system uses something that might be instrumented (and thus call the logging system).   

This argues that that issue should be solved by the logging system and something that works in all cases, and not just the networking case (e.g. what if a logging system wrote to a file and the fIle-I/O was instrumented?)   

Normally you solve this with a ThreadLocal variable that indicates whether you are in the logging system.   You set this when enter the logger and return immediately if you get another callback. (effectively you disable the logger for the duration of the logging operation).  

Arguably this logic should be logger logic that might cause the recursion (that is the thing that subscribed to the operation). 

However since we already have a nice AsyncLocal (Current) it would seem reasonable to 
 
     1) Add a 'bool InLoggingSystem' variable to Activity which something could use to fix this issue
         Document that Activity does not use it, it is just useful for solving this recursion problem.  
     2) Turn this on before the call to DiagnosticSource.Write() in the DiagnosticSource.Start() and Stop().   You can also put it around the activity callback if we keep that.  

This does not completely solve the issue (e.g. DiagnosticSource.Write() that call into AppInsights and if AppInsights does not do something then there will be a problem).   However fetching an async-local is not free, and the scheme above solves all of our issues (since we always use Start and Stop(), and is 'free' in our case since we had to fetch Activity.Current anyway).    It could be made 'perfect' if any logger (and probably already fetches Activity.Current), does the check InLoggingSystem..  

Once we solve this case, I think we are OK.
